# Generated by Django 3.1.5 on 2021-01-17 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210117_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='folder_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.folder'),
        ),
    ]
